[ui]
hideTopBar = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
base="dark"
primaryColor="#1f77b4"
backgroundColor="#212121"
secondaryBackgroundColor="#2f2f2f"
textColor="#ececec"
